# Generated by Django 5.2 on 2025-04-18 10:20

import datetime
import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the fund. Must be unique and under 255 characters.', max_length=255, unique=True, validators=[django.core.validators.MaxLengthValidator(255)])),
                ('strategy', models.CharField(help_text='Select a strategy from the predefined list.', max_length=50)),
                ('aum', models.DecimalField(decimal_places=2, help_text='Assets Under Management (in USD). Must be a positive value.', max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('inception_date', models.DateField(default=datetime.date(2025, 4, 18), help_text='Inception date of the fund (format: YYYY-MM-DD).')),
            ],
        ),
    ]
